/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.geass.gui.searchGUI;



import Client.geass.gui.travellerGUI.TableModel;
import Server.geass.database.DBplan;
import Shared.geass.dataPOJO.Plan;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.FocusEvent;

import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class userPlanPanel extends javax.swing.JPanel {

    /**
     * Creates new form userPlanPanel
     */
    public userPlanPanel() {
        initComponents();
       
        getPlanByuser(null);
        init();
        
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        stackButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setFocusCycleRoot(true);

        jTable1.setModel(plantable);
        jTable1.setName("useplan");
        jScrollPane1.setViewportView(jTable1);

        stackButton.setText("搜一下");
        stackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 315, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stackButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(stackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 199, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 973, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
boolean stack = true ;
boolean begin =true;
    private void stackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stackButtonActionPerformed
        // TODO add your handling code here:
        if(begin){        jSplitPane1.setRightComponent(ps); begin=false;                        }
        if(stack){
        jSplitPane1.setDividerLocation(0.45);
        stack = false ;
        }
        else{
             jSplitPane1.setDividerLocation(1.0);
             stack =true;
        }
    }//GEN-LAST:event_stackButtonActionPerformed
   //  查询某一个用户的计划，刷新表格 可以添加 计划
public void getPlanByuser(ArrayList<Plan> list){
    addPlan(list);
    if(planList==null){
        System.out.println("没有的行程"); 
        return ;
}
    this.plantable.setDataVector(TableModel.getInstance().planTableVector(planList), TableModel.PLAN_COLUMN_NAMES);
}
public void addPlan(ArrayList<Plan> list){
    if((list==null)||(list.size()==0))
        return ;
    else{  for(int i =0 ;i<list.size();i++)
        planList.add(list.get(i));}
}
// 拆分 窗格的 使用
public void init(){
    jSplitPane1.setDividerLocation(1.0);  
      jSplitPane1.setOrientation(JSplitPane.HORIZONTAL_SPLIT);    
    jSplitPane1.setOneTouchExpandable(true);
      
    jSplitPane1.setContinuousLayout(true);
    jSplitPane1.setEnabled(false);
//    jTable1.addMouseListener(listen.getClickListener());
//    jTable1.addMouseMotionListener(listen.getDragListener());
//      Toolkit kit = Toolkit.getDefaultToolkit();    
//					Image img = kit.getImage("src//c.PNG"); 
//					
//					Cursor dynamiteCuror = kit.createCustomCursor(img, new Point(10,10),"dynamite stick") ;    
//                                        setCursor(dynamiteCuror);
   
 }
    
    
    boolean isStack = false ;
    public void cusor(boolean drag ){
    if(drag) {  
  Toolkit kit = Toolkit.getDefaultToolkit();    
					Image img = kit.getImage("src//c.PNG"); 
					
					Cursor dynamiteCuror = kit.createCustomCursor(img, new Point(10,10),"dynamite stick") ;    
                                        setCursor(dynamiteCuror);}
    else
        setCursor(null);
   
}
DBplan dbplan = new DBplan();
    ArrayList<Plan>  planList = dbplan.getPlanByuser("ff");
    
private DefaultTableModel plantable = new DefaultTableModel(null,TableModel.PLAN_COLUMN_NAMES);
Cursor c =null;

private PlanSearchPanel  ps = new PlanSearchPanel(this);
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton stackButton;
    // End of variables declaration//GEN-END:variables
}
